version: '3.1'

services:

    mariadb:
        image: mariadb:10.1
        restart: on-failure
        environment:
            - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
            - "MYSQL_USER=wowstack"
            - "MYSQL_PASSWORD=p4ssw0rd"
            - "MYSQL_DATABASE=wowstack"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
            interval: 1m30s
            timeout: 30s
            retries: 10
        networks:
            - wowstack
        volumes:
            - "mariadb_data:/var/lib/mysql"
            - "./data/mariadb:/docker-entrypoint-initdb.d"

    auth_server:
        image: wowstack/auth-server:latest
        restart: on-failure
        environment:
            - "WOWSTACK_AUTH_DB_HOST=mariadb"
            - "WOWSTACK_AUTH_DB_PORT=3306"
            - "WOWSTACK_AUTH_DB_USERNAME=wowstack"
            - "WOWSTACK_AUTH_DB_PASSWORD=p4ssw0rd"
            - "WOWSTACK_AUTH_DB_DATABASE=wowstack"
            - "WOWSTACK_AUTH_BIND_IP=0.0.0.0"
            - "WOWSTACK_AUTH_BIND_PORT=3724"
        depends_on:
            - mariadb
        ports:
            - "3724:3724"
        networks:
            - wowstack
        volumes:
        - "wowstack_auth_config:/opt/wowstack/etc"

    map_extractors:
        image: wowstack/map-tools:latest
        restart: on-failure
        environment:
            - "WOWSTACK_FORCE_REBUILD=no"
        networks:
            - wowstack
        volumes:
            - "./data/wowstack:/opt/wowstack/share"

    world_server:
        image: wowstack/world-server:latest
        restart: on-failure
        environment:
            - "WOWSTACK_AUTH_DB_HOST=mariadb"
            - "WOWSTACK_AUTH_DB_PORT=3306"
            - "WOWSTACK_AUTH_DB_USERNAME=wowstack"
            - "WOWSTACK_AUTH_DB_PASSWORD=p4ssw0rd"
            - "WOWSTACK_AUTH_DB_DATABASE=wowstack"
            - "WOWSTACK_AUTH_BIND_IP=0.0.0.0"
            - "WOWSTACK_AUTH_BIND_PORT=3724"
            - "WOWSTACK_WORLD_DB_HOST=mariadb"
            - "WOWSTACK_WORLD_DB_PORT=3306"
            - "WOWSTACK_WORLD_DB_USERNAME=wowstack"
            - "WOWSTACK_WORLD_DB_PASSWORD=p4ssw0rd"
            - "WOWSTACK_WORLD_DB_DATABASE=wowstack"
            - "WOWSTACK_WORLD_BIND_IP=0.0.0.0"
            - "WOWSTACK_WORLD_BIND_PORT=8085"
            - "WOWSTACK_CHAR_DB_HOST=mariadb"
            - "WOWSTACK_CHAR_DB_PORT=3306"
            - "WOWSTACK_CHAR_DB_USERNAME=wowstack"
            - "WOWSTACK_CHAR_DB_PASSWORD=p4ssw0rd"
            - "WOWSTACK_CHAR_DB_DATABASE=wowstack"
        depends_on:
            - mariadb
            - map_extractors
            - auth_server
        ports:
            - "8085:8085"
        networks:
            - wowstack
        volumes:
            - "wowstack_world_config:/opt/wowstack/etc"
            - "./data/wowstack:/opt/wowstack/share"

networks:
    wowstack:
        driver: bridge

volumes:
    mariadb_data:
        driver: local
    wowstack_auth_config:
        driver: local
    wowstack_world_config:
        driver: local
